[upd] moved terrabit_saleorder_type to deltatech/deltatech_saleorder_…
dhongu/deltatech pull request #192
Opened 2021-03-12 14:21 UTC by danila12

…type

2021-03-12 18:26 UTC, dhongu requested changes

2021-03-12 18:26 UTC, dhongu commented on deltatech_saleorder_type/tests/test_saleorder_type.py
> +class TestCatalog(TransactionCase):
Poate TestSaleOrder

2021-03-15 05:52 UTC, danila12 commented
Am facut copy/paste si am uitat sa schimb acolo.

2021-03-15 18:41 UTC, dhongu approved these changes

2021-03-16 05:44 UTC, merged