[14.0][ADD]deltatech product tracking
dhongu/deltatech pull request #262
Opened 2021-07-26 10:46 UTC by dhongu

2021-07-27 06:23 UTC, danila12 commented
Atentie, daca se schimba in template-ul de produs trasabilitatea, nu o schimba si in varianta/variante, deci nu se va intampla nimic.

2021-07-27 06:46 UTC, feketemihai commented
Putem face si asta destul de repede?

2021-07-27 10:50 UTC, feketemihai requested changes

2021-07-27 10:50 UTC, feketemihai commented on deltatech_product_tracking/models/product.py
> +        res = super(ProductTemplate, self).write(vals)
Ar trebui sa filtram template si product inainte si sa rulam doar pentru alea, nu pentru toate:

    def write(self, vals):
        templates_without_lot = self.filtered(lambda p: p.tracking == "none")
        res = super(ProductTemplate, self).write(vals)
        if templates_without_lot and vals.get("tracking", "none") == "lot":
            templates_without_lot.mapped("product_variant_ids").fill_lot_in_stock_docs()
        return res

2021-07-27 10:50 UTC, feketemihai commented on deltatech_product_tracking/models/product.py
>      def write(self, vals):
la fel si aici:
    def write(self, vals):
        products_without_lot = self.filtered(lambda p: p.tracking == "none")
        res = super(ProductProduct, self).write(vals)
        if products_without_lot and vals.get("tracking", "none") == "lot":
            products_without_lot.fill_lot_in_stock_docs()
        return res

2021-07-27 10:50 UTC, feketemihai commented on deltatech_product_tracking/models/product.py
> +        warehouses = self.env["stock.warehouse"].with_context(active_test=False).search([])
gasim o varinate pe history, sa actualizam si quant-uri di nalte locatii, adica daca avem transfer prin transit, si quant-urile sunt in tranzit in momentul asta...

2021-07-27 13:37 UTC, danila12 commented
Pare ok.

2021-11-19 08:54 UTC, danila12 approved these changes

2021-11-19 08:56 UTC, dhongu commented
@feketemihai  ce mai trebuie aici ?

2021-11-19 09:17 UTC, feketemihai commented
Salut, nu mai stiu daca e la fel cu ce e  in
https://github.com/NextERP-Romania/war_optimization/tree/14.0/deltatech_product_tracking,
dar undeva isi pierde loturile, adica daca ai receptii neprocesate, dar
pentru care ai deja lot_name completat, noi nu mai verificam asta,
verificam doar lot_id, si atunci le suprascriem...

Cu respect,
Mihai Fekete

NextERP Romania S.R.L.
600B, Peciu Nou, Romania

E-mail: ***@***.***
Telefon: ‪0788-749989‬
Website: https://nexterp.ro



On Fri, Nov 19, 2021 at 10:57 AM Dorin Hongu ***@***.***>
wrote:

> @feketemihai <https://github.com/feketemihai> ce mai trebuie aici ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dhongu/deltatech/pull/262#issuecomment-973879461>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB2MDKZREALTPL4YIFOYLZTUMYGODANCNFSM5A72VN4A>
> .
>

2022-01-05 07:12 UTC, danila12 approved these changes

2025-11-01 01:52 UTC, closed without merging